### ISSUE TITLE
https

### ISSUE THREAD

**Issue by tong** [tong/wtri#6]

**Comment by jonnyAnd** [comment]
Hi, not meaning to try and necro an old project, but https would be be a great addition. Did you have any thoughts on how to implement?

**Comment by tong** [comment]
I have not tried it but there is a ssl socket implementation in the std lib (http://api.haxe.org/sys/ssl/Socket.html) which claims to support server sockets.

**Comment by tong** [comment]
I am using the server behind nginx which handles ssl, therefore won't fix.
